//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by AutoPatchMan.rc
//
#define IDR_MANIFEST                    1
#define ABOUT_BOX_ID_OK                 1
#define DOWNAREA_ID_OK                  2
#define GAMESET_ID_CANCEL               3
#define GAMESET_ID_OK                   4
#define IDC_SOUND_OPTION5               5
#define IDC_GRAPHIC_OPTION13            7
#define IDD_ABOUTBOX                    100
#define IDD_AUTOPATCHMAN_DIALOG         102
#define IDD_GAMESETDLG                  104
#define WARNING_ID_OK                   105
#define IDS_WHQL_CVD                    106
#define IDS_WHQL_UCVD                   107
#define IDS_ABOUTBOX                    108
#define IDC_GRAPHIC_OPTION              109
#define IDC_GRAPHIC_OPTION0             109
#define IDC_GRAPHIC_OPTION1             110
#define IDC_GRAPHIC_OPTION2             111
#define IDC_GRAPHIC_OPTION3             112
#define IDC_GRAPHIC_OPTION4             113
#define IDC_GRAPHIC_OPTION5             114
#define IDC_GRAPHIC_OPTION6             115
#define IDC_GRAPHIC_OPTION7             116
#define IDC_GRAPHIC_OPTION8             117
#define IDC_GRAPHIC_OPTION9             118
#define IDC_GRAPHIC_OPTION10            119
#define IDC_GRAPHIC_OPTION11            120
#define IDC_GRAPHIC_OPTION12            121
#define IDC_SOUND_OPTION                122
#define IDC_SOUND_OPTION0               122
#define IDC_SOUND_OPTION1               123
#define IDC_SOUND_OPTION2               124
#define IDC_SOUND_OPTION3               125
#define IDC_SOUND_OPTION4               126
#define IDS_MESSAGE                     127
#define IDS_MESSAGE0                    127
#define IDR_MAINFRAME                   128
#define IDS_MESSAGE1                    128
#define IDS_MESSAGE2                    129
#define IDR_MAINFRAME_CH                130
#define IDS_MESSAGE3                    130
#define IDS_MESSAGE4                    131
#define IDR_MAINFRAME_MY                132
#define IDS_MESSAGE5                    132
#define IDS_MESSAGE6                    133
#define IDS_MESSAGE7                    134
#define IDS_MESSAGE8                    135
#define IDS_MESSAGE9                    136
#define IDS_MESSAGE10                   137
#define IDS_MESSAGE11                   138
#define IDS_MESSAGE12                   139
#define IDS_MESSAGE13                   140
#define IDS_MESSAGE14                   141
#define IDS_MESSAGE15                   142
#define IDS_MESSAGE16                   143
#define IDS_MESSAGE17                   144
#define IDS_MESSAGE18                   145
#define IDS_MESSAGE19                   146
#define IDS_MESSAGE20                   147
#define IDS_MESSAGE21                   148
#define IDS_MESSAGE22                   149
#define IDS_MESSAGE23                   150
#define IDS_MESSAGE24                   151
#define IDS_MESSAGE25                   152
#define IDS_MESSAGE26                   153
#define IDS_MESSAGE27                   154
#define IDD_DIALOG_WARNING_WHQL         155
#define IDS_MESSAGE28                   156
#define IDS_MESSAGE29                   157
#define IDS_MESSAGE30                   158
#define IDS_MESSAGE31                   159
#define IDS_MESSAGE32                   160
#define IDS_MESSAGE33                   161
#define IDS_MESSAGE34                   162
#define IDS_MESSAGE35                   163
#define IDS_MESSAGE36                   164
#define IDS_MESSAGE37                   165
#define IDS_MESSAGE38                   166
#define IDS_MESSAGE39                   167
#define IDD_DIALOG_DOWNLOAD_AREA        170
#define IDD_GAMESETDLG1                 171
#define IDS_MESSAGE40                   175
#define IDD_GAMESETDLG2                 175
#define IDS_MESSAGE41                   176
#define IDS_MESSAGE42                   177
#define IDS_MESSAGE43                   178
#define IDS_MESSAGE44                   179
#define IDS_MESSAGE45                   180
#define IDS_MESSAGE46                   181
#define IDS_MESSAGE47                   182
#define IDS_MESSAGE48                   183
#define IDS_MESSAGE49                   184
#define IDS_MESSAGE50                   185
#define IDS_MESSAGE51                   186
#define IDS_MESSAGE52                   187
#define IDS_MESSAGE53                   188
#define IDS_MESSAGE54                   189
#define IDS_MESSAGE55                   190
#define IDS_MESSAGE56                   191
#define IDS_MESSAGE57                   192
#define IDS_MESSAGE58                   193
#define IDS_MESSAGE59                   194
#define IDS_MESSAGE60                   195
#define IDS_MESSAGE61                   196
#define IDS_MESSAGE62                   197
#define IDS_MESSAGE63                   198
#define IDS_MESSAGE64                   199
#define IDS_MESSAGE65                   200
#define IDS_MESSAGE66                   201
#define IDS_MESSAGE67                   202
#define IDS_MESSAGE68                   203
#define IDS_MESSAGE69                   204
#define IDS_MESSAGE70                   205
#define IDS_MESSAGE71                   206
#define IDS_MESSAGE72                   207
#define IDS_MESSAGE73                   208
#define IDI_ICON1                       210
#define IDR_MAINFRAME_TW                210
#define IDC_BUTTON_EXIT                 1002
#define IDC_BUTTON_START                1003
#define IDC_PROGRESS_ALL                1004
#define IDC_BUTTON_RETRY                1005
#define IDC_PROGRESS_CUR                1006
#define IDC_STATIC_NOTIFY               1010
#define IDC_COMBO_RESOLUTION            1013
#define IDC_SLIDER_BGM                  1018
#define IDC_SLIDER_SFX                  1019
#define IDC_SLIDER_MAP                  1020
#define IDC_BUTTON_OPTION               1025
#define IDC_COMBO_HZ                    1026
#define IDC_CHECK_SHADOWLAND            1028
#define IDC_CHECK_REALREFLECT           1029
#define IDC_CHECK_REFRACT               1030
#define IDC_COMBO_SHADOWCHAR            1031
#define IDC_COMBO_3DALGORITHM           1032
#define IDC_BUTTON_COMPATIBLE           1033
#define IDC_CHECK_GLOW                  1034
#define IDC_CHECK_NOCHECK               1035
#define IDC_COMBO_SKINDETAIL            1036
#define IDC_CHECK_GAMECURSOR            1037
#define IDC_STATIC_ATI_LINK             1038
#define IDC_CHECK_BUFFEFFECT            1039
#define IDC_CHECK_BGM                   1040
#define IDC_LIST_LOG                    1041
#define IDC_CHECK_MAP                   1042
#define IDC_CHECK_SFX                   1043
#define IDC_COMBO_FOGRANGE              1044
#define IDC_CHECK_TEXTURE_FONT          1045
#define IDC_CHECK_PASSIVE               1046
#define IDC_CHECK_USE_HTTP              1047
#define IDC_CHECK_FRAME_LIMIT           1047
#define IDC_BUTTON_PATCH                1048
#define IDC_CHECK_WINDOWMODE            1049
#define IDC_COMBO_DEFAULTOPTION         1050
#define IDC_CHECK_3DSOUND               1051
#define IDC_READYTOSTART                1052
#define IDC_RADIO_AREA1                 1053
#define IDC_CHECK_POSTPROCESSING        1054
#define IDC_RADIO_AREA2                 1055
#define IDC_RADIO_AREA3                 1056
#define IDC_RADIO_AREA4                 1057
#define IDC_RADIO1                      1058
#define IDC_RADIO_AREA5                 1058
#define IDC_RADIO2                      1059
#define IDC_RADIO_AREA6                 1059
#define IDC_RADIO3                      1060
#define IDC_RADIO_AREA7                 1060
#define IDC_VER_STATIC                  1061
#define IDC_RADIO5                      1061
#define IDC_RADIO4                      1062
#define IDC_TITLE_STATIC                1063
#define IDC_RADIO6                      1063
#define IDC_AREA_STATIC                 1064
#define IDC_RADIO7                      1064
#define IDC_VIDEO_STATIC                1065
#define IDC_NVIDIA_STATIC               1066
#define IDC_ATI_STATIC                  1067
#define IDC_DISPLAY_STATIC              1068
#define IDC_GRAPHIC_STATIC              1069
#define IDD_ABOUT_BOX                   1069
#define IDC_DEFAULT_OPTION_STATIC       1070
#define IDC_FOGRANGE_STATIC             1071
#define IDC_SHADOWCHAR_STATIC           1072
#define IDC_SOUND_STATIC                1073
#define IDC_BGM_STATIC                  1074
#define IDC_MAP_STATIC                  1075
#define IDC_SFX_STATIC                  1076
#define IDC_DOWNLOAD_STATIC             1077
#define IDC_DOWNAREA_STATIC             1078
#define IDC_STATIC_NVIDIA_LINK          1079
#define IDC_SKINDETAIL_STATIC           1080
#define IDM_ABOUTBOX                    1081

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        211
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1083
#define _APS_NEXT_SYMED_VALUE           105
#endif
#endif
